<!DOCTYPE html>

<!--
<b>Erro 404 View</b>
Esta página é exibida quando o usuário tentar ou ser levado para um controller ou action inexistente.
@copyright (c) Junho, 2015, Anderson B. Glaeser - F5 Digital.
-->

<html lang="pt-br">
    <head>
        <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
        <meta charset="utf-8" />
        <title>Erro 404</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta content="Anderson Glaeser" name="author" />
    </head>

    <body>
        Página de erro
    </body>
</html>